version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
          - "github.com/agoda-com/opentelemetry-logs-go*"
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      prometheus:
        patterns:
          - "github.com/prometheus/*"
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker
