FROM --platform=linux/amd64 golang:1.23-alpine as build-stage
# Set destination for COPY
WORKDIR /app
RUN apk add --no-cache --update go gcc g++ bash git
RUN echo "unicode=\"YES\"" >> /etc/rc.conf && \
    apk add --no-cache --virtual .build_deps \
        autoconf file libc-dev make pkgconf python3 py3-pip ninja \
        util-linux pciutils usbutils coreutils binutils findutils grep \
        build-base abuild binutils binutils-doc gcc-doc gperf libcap libcap-dev \
        valgrind-dev libmount && pip3 install meson --break-system-packages 

RUN cd /tmp && git clone https://github.com/systemd/systemd

# RUN cd /tmp/systemd && \
#     meson build && \
#     ninja build

RUN apk add elogind-dev

COPY go.mod go.sum ./

RUN  go mod download 

COPY ./ ./
ARG VERSION=unknown
RUN CGO_ENABLED=1 go build -mod=readonly -ldflags "-X main.version=$VERSION" -o coroot-node-agent .

FROM --platform=linux/amd64 alpine:3.19 AS release-stage
WORKDIR /app
COPY --from=build-stage /app/coroot-node-agent /usr/bin/coroot-node-agent
RUN chmod +x /usr/bin/coroot-node-agent
CMD ["coroot-node-agent"]