name: dev build image
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/nudgebee/logparser
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Create tag name
        run: echo "tag=$(date +'%Y-%m-%dT%H-%M-%S')_$GITHUB_SHA" >> $GITHUB_ENV

      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and Push Agent Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 'Dockerfile.alpine'
          push: true
          tags: |
            280501305789.dkr.ecr.us-east-1.amazonaws.com/nudgebee-node-agent:${{ env.tag }}
